# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

expand_similarity_cpp <- function(indices, simmat, thresh) {
    .Call(`_adjoin_expand_similarity_cpp`, indices, simmat, thresh)
}

expand_similarity_below_cpp <- function(indices, simmat, thresh) {
    .Call(`_adjoin_expand_similarity_below_cpp`, indices, simmat, thresh)
}

cross_fspatial_weights <- function(indices, distances, feature_mat1, feature_mat2, sigma, fsigma, alpha, maxk, binary) {
    .Call(`_adjoin_cross_fspatial_weights`, indices, distances, feature_mat1, feature_mat2, sigma, fsigma, alpha, maxk, binary)
}

bilateral_weights <- function(indices, distances, feature_mat, sigma, fsigma) {
    .Call(`_adjoin_bilateral_weights`, indices, distances, feature_mat, sigma, fsigma)
}

fspatial_weights <- function(indices, distances, feature_mat, sigma, fsigma, alpha, binary) {
    .Call(`_adjoin_fspatial_weights`, indices, distances, feature_mat, sigma, fsigma, alpha, binary)
}

spatial_weights <- function(indices, distances, sigma, binary) {
    .Call(`_adjoin_spatial_weights`, indices, distances, sigma, binary)
}

